before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  # Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbt-version


stages:
- build
- deploy

build_job:
  stage: build
  script:
  - sbt clean playGenerateSecret  stage  dist

deploy_job:
  stage: deploy
  script:
  - target/universal/stage/bin/./kunderadatabasecloud -J-Xms1280M -J-Xmx2120m -J-server -Dconfig.file=target/universal/stage/conf/application.conf  -Dhttp.port=9220 > LOG.txt
