stages:
- build
- deploy

build_job:
  stage: build
  script:
  - sbt clean playGenerateSecret  stage  dist

deploy_job:
  stage: deploy
  script:
  - target/universal/stage/bin/./kunderadatabasecloud -J-Xms1280M -J-Xmx2120m -J-server -Dconfig.file=target/universal/stage/conf/application.conf  -Dhttp.port=9220 > LOG.txt
